apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo.fullname" . }}-postgres-secrets
type: Opaque
data:
  password: {{ .Values.secrets.postgresPassword | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo.fullname" . }}-backend-secrets
type: Opaque
data:
  secret-key: {{ .Values.secrets.backendSecretKey | b64enc | quote }}
  openai-api-key: {{ .Values.secrets.openaiApiKey | default "" | b64enc | quote }}